import re

import pytest
from app.utils.security.tokens import create_token


@pytest.fixture
def verification_token():
    """Fixture to provide a verification token for testing."""
    return create_token()


def test_create_verification_token_type(verification_token):
    """
    Test the `create_verification_token` function to ensure it generates a token
    with the expected structure and content.
    """
    assert isinstance(verification_token, str)


def test_create_verification_token_length(verification_token):
    """
    Test the length of the token generated by `create_verification_token`.
    The token should be URL-safe and typically 43 characters long.
    """
    assert len(verification_token) == 43


def test_create_verification_token_format(verification_token):
    """
    Test the format of the token generated by `create_verification_token`.
    The token should be URL-safe, containing alphanumeric characters and hyphens.
    """
    assert re.match(r"^[A-Za-z0-9_-]+$", verification_token)
