services:
  database:
    build: ./database
    environment:
      POSTGRES_DB: authentication-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - auth_service_db:/var/lib/postgresql/data
      - ./postgresql.conf:/custom-config/postgresql.conf:ro
    command: postgres -c config_file=/custom-config/postgresql.conf
    networks:
      - auth_network
    restart: unless-stopped

  api:
    build: ./api
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: authentication-service
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8000:8000'
    networks:
      - auth_network
    restart: unless-stopped

  pg_backup:
    image: postgres:17.5
    depends_on:
      - database
    volumes:
      - ./backups:/backup
    networks:
      - auth_network
    command: pg_dump -h database -U postgres -d authentication-service -f ./backup/auth_db_$(date +%Y%m%d_%H%M%S).sql
    profiles:
      - backup

volumes:
  auth_service_db:
    driver: local

networks:
  auth_network:
