---
name: Create Release

permissions:
  contents: write
  pull-requests: read
  statuses: read

on:
  push:
    branches:
      - 'main'
    paths:
      - 'database/sql/**/*.sql'
      - 'api/app/v*/**/*.py'

jobs:
  suggest-bump:
    uses: ./.github/workflows/suggest-version-bump.yml

  create-release:
    name: Create Release
    needs: suggest-bump
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Using the current version since this workflow is triggered by a push to main
          tag_name: "v${{ needs.suggest-bump.outputs.service_current_version }}"
          release_name: "Version ${{ needs.suggest-bump.outputs.service_current_version }}"
          draft: false
          prerelease: ${{ startsWith(needs.suggest-bump.outputs.service_current_version, '0') }}
