---
name: Get PR Labels

permissions:
  contents: read
  statuses: read
  pull-requests: read

on:
  workflow_call:
    outputs:
      labels:
        description: 'Labels on the pull request'
        value: ${{ jobs.get-labels.outputs.labels }}

jobs:
  get-labels:
    name: Get PR Labels
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.labels.outputs.labels }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR labels
        id: labels
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ] && [ -n "${{ github.event.pull_request.number }}" ]; then
            LABELS=$(gh pr view "${{ github.event.pull_request.number }}" --json labels --jq '[.labels[].name] | join(" ")')
          else
            # No PR context, return empty labels
            LABELS=""
          fi
          echo "labels=$LABELS" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
